package pojo;
// Generated Oct 11, 2022 9:33:22 PM by Hibernate Tools 4.3.1


import java.util.Date;  
import javax.persistence.Column;  
import javax.persistence.Entity;  
import javax.persistence.GeneratedValue;  
import static javax.persistence.GenerationType.IDENTITY;  
import javax.persistence.Id;  
import javax.persistence.Table;  
import javax.persistence.Temporal;  
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */

@Entity  
@Table(name = "user", catalog = "test")  
public class User implements java.io.Serializable  
{  
     private Integer id;
     private String recordNo;
     private String name;
     private String address;
     private String car;
     private Date dob;
     private String email;

    public User() {
    }

    public User(String recordNo, String name, String address, String car, Date dob, String email) {
       this.recordNo = recordNo;
       this.name = name;
       this.address = address;
       this.car = car;
       this.dob = dob;
       this.email = email;
    }
   
    @Id @GeneratedValue(strategy = IDENTITY)  
    @Column(name = "id", unique = true, nullable = false)  
    public Integer getId()  
    {  
        return this.id;  
    }  
    public void setId(Integer id)  
    {  
        this.id = id;  
    }  
    
   @Column(name = "RecordNo", length = 20)  
    public String getRecordNo()  
    {  
        return this.recordNo;  
    }  
    public void setRecordNo(String recordNo)  
    {  
        this.recordNo = recordNo;  
    }  
    @Column(name = "Name", length = 50)  
    public String getName()  
    {  
        return this.name;  
    }  
    public void setName(String name)  
    {  
        this.name = name;  
    }  
    @Column(name = "Address", length = 50)  
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    @Column(name = "Car", length = 50) 
    public String getCar() {
        return this.car;
    }
    
    public void setCar(String car) {
        this.car = car;
    }
    @Temporal(TemporalType.DATE)  
    @Column(name = "Dob", length = 10)  
    public Date getDob()  
    {  
        return this.dob;  
    }  
    public void setDob(Date dob)  
    {  
        this.dob = dob;  
    }  
    @Column(name = "Email", length = 50)  
    public String getEmail()  
    {  
        return this.email;  
    }  
    public void setEmail(String email)  
    {  
        this.email = email;  
    }  
    
    //This method writes the values of contact object with System.out.println(user.toString()) code  
    @Override  
    public String toString()  
    {  
        return "user" +  
            "\n\t RecordNo: " + this.recordNo +  
            "\n\t CustomerName: " + this.name +  
            "\n\t Address: " + this.address +  
            "\n\t Car: " + this.car +  
            "\n\t Date of Booking: " + this.dob +  
            "\n\t Email: " + this.email;  
    } 
    

} 

